# Generated by Django 5.1.6 on 2025-06-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('cadena', models.CharField(blank=True, max_length=20, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
            ],
            options={
                'db_table': 'link',
            },
        ),
    ]
