# Generated by Django 5.1.6 on 2025-06-03 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuitIdentity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circuitidentity',
            old_name='links',
            new_name='link_id',
        ),
    ]
