# Generated by Django 5.1.6 on 2025-06-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('public_AWS', models.CharField(max_length=100, null=True)),
                ('private_AWS', models.CharField(max_length=100, null=True)),
                ('s3_AWS', models.CharField(max_length=100, null=True)),
                ('token_IBM', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'deployment',
            },
        ),
    ]
